<?php

return [
    'title' => 'Terminos y Condiciones',
    'p1' => 'Al descargar o usar la aplicación, estos términos se aplicarán automáticamente a usted; por lo tanto, debe asegurarse de leerlos detenidamente antes de usar la aplicación. No se le permite copiar ni modificar la aplicación, ninguna parte de la aplicación o nuestras marcas comerciales de ninguna manera. No puede intentar extraer el código fuente de la aplicación y tampoco debe intentar traducir la aplicación a otros idiomas o hacer versiones derivadas. La aplicación en sí, y todas las marcas comerciales, derechos de autor, derechos de bases de datos y otros derechos de propiedad intelectual relacionados con ella, aún pertenecen a Cristian Savino.',
    'p2' => 'Cristian Savino se compromete a garantizar que la aplicación sea lo más útil y eficiente posible. Por ese motivo, nos reservamos el derecho de realizar cambios en la aplicación o de cobrar por sus servicios, en cualquier momento y por cualquier motivo. Nunca le cobraremos por la aplicación o sus servicios sin dejarle muy claro exactamente por qué está pagando.',
    'p3' => 'La aplicación Fulbito App almacena y procesa los datos personales que nos ha proporcionado para poder prestar mi Servicio. Es su responsabilidad mantener su teléfono y el acceso a la aplicación seguros. Por lo tanto, le recomendamos que no haga jailbreak ni rootee su teléfono, que es el proceso de eliminar las restricciones y limitaciones de software impuestas por el sistema operativo oficial de su dispositivo. Podría hacer que su teléfono sea vulnerable a malware / virus / programas maliciosos, comprometer las funciones de seguridad de su teléfono y podría significar que la aplicación Fulbito App no funcionará correctamente o no funcionará en absoluto.',
    'p4' => 'La aplicación utiliza servicios de terceros que declaran sus propios términos y condiciones.',
    'p5' => 'Enlace a los términos y condiciones de los proveedores de servicios externos utilizados por la aplicación',
    'p6' => 'Debe tener en cuenta que hay ciertas cosas de las que Cristian Savino no se responsabiliza. Ciertas funciones de la aplicación requerirán que la aplicación tenga una conexión a Internet activa. La conexión puede ser Wi-Fi o provista por su proveedor de red móvil, pero Cristian Savino no puede asumir la responsabilidad de que la aplicación no funcione con todas sus funciones si no tiene acceso a Wi-Fi y no tiene ninguno de queda su asignación de datos.',
    'p7' => 'Si está utilizando la aplicación fuera de un área con Wi-Fi, debe recordar que los términos del acuerdo con su proveedor de red móvil se seguirán aplicando. Como resultado, su proveedor de telefonía móvil puede cobrarle el costo de los datos durante la duración de la conexión mientras accede a la aplicación, u otros cargos de terceros. Al usar la aplicación, acepta la responsabilidad de dichos cargos, incluidos los cargos de datos de roaming si usa la aplicación fuera de su territorio de origen (es decir, región o país) sin desactivar el roaming de datos. Si no es el pagador de facturas del dispositivo en el que está utilizando la aplicación, tenga en cuenta que asumimos que ha recibido el permiso del pagador de facturas para utilizar la aplicación.',
    'p8' => 'En la misma línea, Cristian Savino no siempre puede asumir la responsabilidad de la forma en que usa la aplicación, es decir, debe asegurarse de que su dispositivo permanezca cargado, si se queda sin batería y no puede encenderlo para hacer uso del Servicio, Cristian Savino no puede aceptar la responsabilidad.',
    'p9' => 'Con respecto a la responsabilidad de Cristian Savino por su uso de la aplicación, cuando esté utilizando la aplicación, es importante tener en cuenta que, aunque nos esforzamos por asegurarnos de que esté actualizada y sea correcta en todo momento, confiamos en terceros para proporcionarnos información para que podamos ponerla a su disposición. Cristian Savino no acepta ninguna responsabilidad por cualquier pérdida, directa o indirecta, que experimente como resultado de confiar completamente en esta funcionalidad de la aplicación.',
    'p10' => 'En algún momento, es posible que deseemos actualizar la aplicación. La aplicación está disponible actualmente en Android & amp; iOS: los requisitos para ambos sistemas (y para cualquier sistema adicional al que decidamos extender la disponibilidad de la aplicación) pueden cambiar, y deberá descargar las actualizaciones si desea seguir usando la aplicación. Cristian Savino no promete que siempre actualizará la aplicación para que sea relevante para usted y / o funcione con Android & amp; Versión de iOS que ha instalado en su dispositivo. Sin embargo, usted promete aceptar siempre las actualizaciones de la aplicación cuando se le ofrezcan. También es posible que deseemos dejar de proporcionar la aplicación y podemos cancelar su uso en cualquier momento sin notificarle la terminación. A menos que le indiquemos lo contrario, en caso de rescisión, (a) los derechos y licencias otorgados a usted en estos términos terminarán; (b) debe dejar de usar la aplicación y (si es necesario) eliminarla de su dispositivo.',
    'title.p11' => 'Cambios a estos términos y condiciones',
    'p11' => 'Puedo actualizar nuestros Términos y condiciones de vez en cuando. Por lo tanto, le recomendamos que revise esta página periódicamente para ver si hay cambios. Le notificaré cualquier cambio mediante la publicación de los nuevos Términos y condiciones en esta página.',
    'p12' => 'Estos términos y condiciones son efectivos a partir del 2021-08-12.',
    'title.p13' => 'Contacta con nosotros',
    'p13' => 'Si tiene alguna pregunta o sugerencia sobre mis Términos y condiciones, no dude en ponerse en contacto con nosotros en thefulbitoapp@gmail.com.'
];
